### ISSUE TITLE
create mean, median, mode class

### ISSUE THREAD

**Issue by Ehimmell** [Ehimmell/sp500Info#32]
python has built in methods to get the mean, median, and mode of a data set. make a class to call the stock data table from the database, filter it out to get just closing prices, and find the mean, median, and mode of the data

update- use the getDailyStock method from data interact.py to Get a pandas data frame of stock prices and data. filter this column to find closing prices and use them to find the mean.

**Comment by shark-lamp** [comment]
Hi Ehimmell! I'm Sahej, a beginner in open source. I want to start working on this task. can I be assigned?

**Comment by Ehimmell** [comment]
I invited you to collaborate, you can assign yourself once you accept

**Comment by bishnoi322** [comment]
Hi Ehimmel, I came across your issue and came up with a solution : 
[Central_tendency.txt](https://github.com/Ehimmell/sp500Info/files/15084823/Central_tendency.txt)
Hope it helps!

**Comment by bishnoi322** [comment]
Hey Ehimmell, I'm Kanchan and a beginner in open source. Can i get a look at the task?

**Comment by bishnoi322** [comment]
i meant i want to collaborate

**Comment by Ehimmell** [comment]
sure, i can email you or contact you somewhere else if that's what you prefer with details about what i was thinking to get this done

**Comment by ZKay47** [comment]
up yours Sahej, its all mine

**Comment by bishnoi322** [comment]
You can assign it here. but in any case here's my email id : kanchanbishnoi29@outlook.com.

**Comment by Ehimmell** [comment]
@ZKay47 you doing this or not
